TK2_PPW/urls.py
import django
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_register.urls')),

    path('', include('home.urls')),
    path('form/', include('form.urls')),
    path('info/', include('info.urls')),
    path('article/', include('article.urls')),
    path('news/', include('news.urls')),
]

article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:id>', views.detail, name="detail"),
    path('tags/<str:name>', views.tags, name="tags"),
    path('register', views.register, name="register"),
    path('register_tags', views.register_tags, name="register_tags"),
    path('api', views.api_article, name="api_article"),
    path('api/tags', views.api_tags, name="api_tags"),
]

form/urls.py
from django.urls import path

from . import views
from form.views import UserCreateView

app_name = 'form'

urlpatterns = [
    path('', UserCreateView.as_view(), name='form'),
    path('success/', views.success, name='success'),
    path('patient/', views.patient_list, name='patient_list'),
    path('details/<int:pk>', views.patient_details, name='patient_details'),
    path('delete/<int:pk>', views.delete_patient, name='delete_patient'),
    path('search/', views.search_patient, name='search_patient'),
    path('case/', views.add_case, name='add_case'),
]

article/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    text = models.TextField()
    image = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Tags(models.Model):
    name = models.CharField(max_length=100)
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        related_name='tags'
    )

    def __str__(self):
        return self.name

article/forms.py
from django.forms import ModelForm
from .models import Article, Tags


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'author', 'text', 'image']

class TagsForm(ModelForm):
    class Meta:
        model = Tags
        fields = ['name', 'article']

article/views.py
from django.http import request, JsonResponse
from django.shortcuts import redirect, render
from .models import Article, Tags
from .forms import ArticleForm, TagsForm


def index(request):
    context = {'page_title': 'Article Corona Terbaru'}
    return render(request, "article/index.html", context)


def detail(request, id):
    article = Article.objects.get(id=id)
    context = {'page_title': article.title, 'id': id}
    return render(request, "article/detail.html", context)


def tags(request, name):
    context = {'page_title': name, 'name':name}
    return render(request, "article/tags.html", context)


def register(request):
    form_article = ArticleForm()
    if request.method == 'POST':
        form_article = ArticleForm(request.POST)
        if form_article.is_valid():
            form_article.save()
        return redirect('article:index')
    context = {'page_title': 'register', 'form_article': form_article}
    return render(request, "article/register.html", context)


def register_tags(request):
    form_tags = TagsForm()
    if request.method == 'POST':
        form_tags = TagsForm(request.POST)
        if form_tags.is_valid():
            data = [x.strip() for x in request.POST['name'].split(',')]
            request.POST._mutable = True
            for i in data:
                request.POST['name'] = i
                TagsForm(request.POST).save()
        return redirect('article:index')
    context = {'page_title': 'register', 'form_tags': form_tags}
    return render(request, "article/register_tags.html", context)


def api_article(request):
    data = []
    articles = None
    if 'id' in request.GET:
        id = request.GET['id']
        articles = Article.objects.filter(id=id)
    else:
        articles = Article.objects.all()
    for article in articles:
        tags = []
        for tag in Tags.objects.filter(article=article.id):
            tags.append(str(tag))
        dct = {k:v for k, v in article.__dict__.items() if not k.startswith('_')}
        dct['tags'] = tags
        data.append(dct)
    return JsonResponse(data, json_dumps_params={'indent': 2}, safe=False)


def api_tags(request):
    name = request.GET['name']
    data = []
    for tag in Tags.objects.filter(name=name):
        article = Article.objects.get(id=tag.article_id)
        article = {k:v for k, v in article.__dict__.items() if not k.startswith('_')}
        tags = []
        for inner_tag in Tags.objects.filter(article=article['id']):
            tags.append(str(inner_tag))
        article.update({'tags': tags})
        data.append(article)
    return JsonResponse(data, json_dumps_params={'indent': 2}, safe=False)

article/templates/article/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@200;300;400;500;600;700&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="{% static 'article/style.css' %}" />
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="{% static 'article/script.js' %}" defer></script>
  <title>{{ page_title }}</title>
</head>

<body>
  <!-- Header -->
  {% include "home/navbar.html" %}

  <div class="content">
    {% block content %}
    {% endblock content %}

    <!-- Footer -->
      {% include "home/footer.html" %}
  </div>
</body>

</html>

article/templates/article/detail.html
{% extends 'article/base.html' %}

{% block content  %}
<script defer>$(document).ready(() => {loadArticle('{{ id }}', 'article')})</script>
<div class="article">

</div>

{% endblock %}

article/templates/article/index.html
{% extends 'article/base.html' %}

{% block content  %}
<script defer>$(document).ready(() => {loadArticle(undefined,'all')})</script>
<h1>Article Terbaru Corona</h1>
{% if user.is_authenticated %}
<h4><a class="btn btn-primary" href="{% url 'article:register' %}">Daftarkan Artikelmu</a></h4>
<h4><a class="btn btn-primary" href="{% url 'article:register_tags' %}">Daftarkan Tags Artikelmu</a></h4>
{% endif %}

<div class="article"></div>
{% endblock  %}

article/templates/article/register.html
{% extends 'article/base.html' %}

{% block content  %}
<h1> Register Article </h1>
<div>
  <form method="POST">
    <table>
      {% csrf_token %}
      {{ form_article.as_table }}
      <!-- {{ form_tags.as_table }} -->
    </table>
    <input class="btn" type="submit" value="Submit" />
  </form>
</div>

{% endblock  %}

article/templates/article/register_tags.html
{% extends 'article/base.html' %}

{% block content  %}
<h1> Register Article Tags </h1>
<div>
  <form method="POST">
    {% csrf_token %}
    {{ form_tags.as_p }}
    <input class="btn" type="submit" value="Submit" />
  </form>
</div>

{% endblock  %}

article/templates/article/tags.html
{% extends 'article/base.html' %}

{% block content  %}
<h1>Article Berdasarkan</h1>
<script defer>$(document).ready(() => {loadArticle('{{ name }}', 'tags' )})</script>


<div class="article"></div>
{% endblock  %}