TK2_PPW/urls.py
import django
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_register.urls')),

    path('', include('home.urls')),
    path('form/', include('form.urls')),
    path('info/', include('info.urls')),
    path('article/', include('article.urls')),
    path('news/', include('news.urls')),
]

form/urls.py
from django.urls import path

from . import views
from form.views import UserCreateView

app_name = 'form'

urlpatterns = [
    path('', UserCreateView.as_view(), name='form'),
    path('success/', views.success, name='success'),
    path('patient/', views.patient_list, name='patient_list'),
    path('details/<int:pk>', views.patient_details, name='patient_details'),
    path('delete/<int:pk>', views.delete_patient, name='delete_patient'),
    path('search/', views.search_patient, name='search_patient'),
    path('case/', views.add_case, name='add_case'),
]

home/urls.py
from django.urls import path
from . import views

app_name= 'home'

urlpatterns = [
    path('', views.index, name='index')
]

login_register/urls.py
from django.urls import path

from .views import sign_up_page, loginView,  logoutUser

app_name= 'login_register'

urlpatterns = [
    path('signup/', sign_up_page, name='signup'),
    path('login/', loginView, name='login'),
    # path('loginAPI/', loginAPI, name='loginAPI'),
    path('logout/', logoutUser, name='logout')
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.index, name="index"),
    path('lapor', views.hoax, name="hoax"),
    path('api/fetch', views.fetch, name="fetch"),
    path('api/get', views.getBulk, name="news"),
]

news/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

# Create your models here.

# # TODO: Delete outlet class
# class Outlet(models.Model):

#     name = models.CharField(max_length=50)

#     class Meta:
#         verbose_name = _("Outlet")
#         verbose_name_plural = _("Outlets")

#     def __str__(self):
#         return self.name

#     def get_absolute_url(self):
#         return reverse("Outlet_detail", kwargs={"pk": self.pk})

class News(models.Model):

    title = models.CharField(max_length=100)
    url = models.URLField(max_length=200)
    unix_time = models.CharField(max_length=50)
    description = models.CharField(max_length=200, null=True)
    img = models.CharField(max_length=1000, null=True)
    outlet = models.CharField(max_length=1000)

    class Meta:
        verbose_name = _("News")
        verbose_name_plural = _("News")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("News_detail", kwargs={"pk": self.pk})

class HoaxReport(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    judul = models.CharField(max_length=100)
    text = models.TextField()
    url = models.URLField(max_length=200)
    message = models.TextField()
    
    # bookmarks = models.JSONField(blank=True)

    def __str__(self):
        return self.user.username

news/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from .models import HoaxReport


class HoaxForm(ModelForm):
    """
    Form for Hoax submission
    """
    text = forms.CharField(widget=forms.Textarea)
    message = forms.CharField(widget=forms.Textarea)
    
    class Meta:
        model = HoaxReport
        fields = ['judul', 'text', 'url', 'message']
        widgets = {
            'text': Textarea(),
            'message': Textarea(),
        }

news/views.py
import re
from django.http import JsonResponse, HttpResponse
from django.core import serializers, paginator
from django.shortcuts import render
from urllib3 import PoolManager
from bs4 import BeautifulSoup
from .models import News
from .forms import HoaxForm

uri = re.compile(r"^(?:https?:\/\/)?(?:[^@\/\n]+@)?(?:www\.)?([^:\/?\n]+)")
news = None

# Create your views here.


def index(request):
    request.session['page'] = 1
    return render(request, "news/news-index.html")


def fetch(request):
    page = dict(request.GET)

    if not News.objects.filter(title=page["title"][0]).exists():
        outlet_name = uri.match(page["url"][0])[1]
        desc, img = getMeta(page["url"][0])

        news, _ = News.objects.get_or_create(
            title=page["title"][0],
            url=page["url"][0],
            unix_time=str(page["timestamp"][0]),
            description=desc,
            img=img,
            outlet=outlet_name,
        )
        news.save()
        return HttpResponse('Added')
        # outlet = Outlet.objects.get_or_create(name)
    return HttpResponse('Skipped')


def getBulk(request):
    global news

    if (news == None):
        news = paginator.Paginator(News.objects.order_by('-unix_time'), 5)

    page_num = request.session.get('page')
    if not page_num:
        page_num = 1

    if (news.num_pages >= page_num):
        try:
            ret_news = news.page(page_num)
            page_num += 1
            request.session['page'] = page_num
            return HttpResponse(serializers.serialize("json", list(ret_news.object_list)), content_type="application/json") # Manually serialize
        except:
            return JsonResponse({'error': 'true'}, safe=False)

    return JsonResponse({'empty': 'true'}, safe=False)


def hoax(request):
    context = {}
    if request.method == 'POST':
        form = context['form'] = HoaxForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            context['success'] = True
            form.save()

    else:
        context['form'] = HoaxForm()

    return render(request, "news/form.html", context=context)


def getMeta(url: str):
    """
    Helper function to fetch metadata
    """
    response = PoolManager().request('GET', url)
    soup = BeautifulSoup(response.data, features="html.parser")

    desc = soup.find("meta",  property="og:description")
    img = soup.find("meta", property="og:image")

    desc = desc["content"] if desc else None
    img = img["content"] if img else None

    return desc, img

news/templates/news/base.html
<!DOCTYPE html>

{% load static %}

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block head %}
        {% endblock head %}

        {% block script_head %}
        {% endblock script_head %}

        {% block style %}
        {% endblock style %}
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        {% block body %}
            <div id="page-container">
                <div id="content-wrap">
            {% include "home/navbar.html" %}
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
            {% include "home/footer.html" %}
        {% endblock body %}
        
        {% block script_foot %}
        {% endblock script_foot %}
    </body>
</html>

news/templates/news/form.html
{% extends 'news/base.html' %}
{% load static %}
{% load widget_tweaks %}
<!-- Title -->
{% block head %}
<title>Lapor Hoax | Form Corona</title>
{% endblock head %}
<!-- Header -->
{% block style %}
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@200;300;400;500;600;700&display=swap"rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" />
<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/news-ui.css' %}" />
{% endblock style %}
<!-- Content -->
{% block content %}
<div class="container pt-10 my-12 mx-auto px-4 md:px-12">

    {% if success %}
    <div class="alert alert-success">
        <strong>Laporan anda berhasil disimpan!</strong>
    </div>
    {% endif %}


    <div class="mx-auto container max-w-2xl md:w-3/4 shadow-md">
        <div class="p-4 text-3xl text-center">
            <div class="max-w-sm mx-auto md:w-full md:mx-0">
                <div class="inline-flex items-center space-x-4 ">
                    <h1 class="text-gray-600">Lapor Hoax</h1>
                </div>
            </div>
        </div>
        {% if user.is_authenticated %}
        <div class="bg-gray-100 p-4 border-t-2 bg-opacity-5 border-green-400 rounded-t text-center">
            <div class="max-w-sm mx-auto md:w-full md:mx-0">
                <div class="inline-flex items-center space-x-4">
                    <h1 class="text-gray-600">Melapor sebagai:</h1>
                </div>
                <div class="inline-flex items-center space-x-4">
                    <h1 class="text-gray-600 font-bold">{{ user.username }} ({{ user.email }})</h1>
                </div>
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="bg-white space-y-6">
                <div class="md:inline-flex space-y-4 md:space-y-0 w-full p-4 text-gray-500 items-center">
                    <h2 class="md:w-1/3 max-w-sm mx-auto">Judul laporan</h2>
                    <div class="md:w-2/3 max-w-sm mx-auto">
                        <div class="w-full inline-flex border">
                            {% render_field form.judul class+="w-11/12 focus:outline-none focus:text-gray-600 p-2" placeholder="Disinformasi Vaksin" %}
                        </div>
                    </div>
                </div>
                <hr />
                <div class="md:inline-flex  space-y-4 md:space-y-0  w-full p-4 text-gray-500 items-center">
                    <h2 class="md:w-1/3 mx-auto max-w-sm">Data laporan</h2>
                    <div class="md:w-2/3 mx-auto max-w-sm space-y-5">
                        <div>
                            <label class="text-sm text-gray-400">URL Informasi Hoax</label>
                            <div class="w-full inline-flex border">
                                {% render_field form.url class+="w-11/12 focus:outline-none focus:text-gray-600 p-2" placeholder="www.example.com" %}
                            </div>
                            <label class="text-sm text-red-400">{{ form.url.errors }}</label>
                        </div>
                        <div>
                            <label class="text-sm text-gray-400">Bagian teks yang mengandung hoax/disinformasi</label>
                            <div class="w-full inline-flex border">
                            {% render_field form.text class+="w-11/12 focus:outline-none focus:text-gray-600 p-2" placeholder="Vaksin mengandung ..." %}
                            </div>
                            <label class="text-sm text-red-400">{{ form.text.errors }}</label>
                        </div>
                    </div>
                </div>
                <hr />
                <div class="md:inline-flex  space-y-4 md:space-y-0  w-full p-4 text-gray-500 items-center">
                    <h2 class="md:w-1/3 mx-auto max-w-sm">Pesan anda ke penyidik</h2>
                    <div class="md:w-2/3 mx-auto max-w-sm space-y-5">
                        <div>
                            <div class="w-full inline-flex border">
                                {% render_field form.message class+="w-11/12 focus:outline-none focus:text-gray-600 p-2" placeholder="Masukan informasi untuk mempermudah penyidikan" %}
                            </div>
                            <label class="text-sm text-red-400">{{ form.message.errors }}</label>
                        </div>
                    </div>
                </div>
                <hr />
                <div class="md:inline-flex w-full md:space-y-0 p-8 text-gray-500 items-center text-middle m-0">
                    <div class="md:w-3/12 text-center md:pl-6 m-auto">
                    <input type="submit" value="Lapor" class="inline-block px-6 py-2 text-xs font-medium leading-6 text-center text-white uppercase transition bg-green-500 rounded shadow ripple hover:shadow-lg hover:bg-green-600 focus:outline-none">
                    </div>
                </div>
            </div>
        </form>
        {% else %}
        <div class="bg-gray-100 p-4 border-t-2 bg-opacity-5 border-green-400 rounded-t text-center">
            <div class="max-w-sm mx-auto md:w-full md:mx-0">
                <div class="inline-flex items-center space-x-4">
                    <h1 class="text-gray-600">Anda belum login,</h1>
                </div>
                <div class="inline-flex items-center space-x-4">
                    <h1 class="text-gray-600 font-bold"><a href={% url 'login_register:login' %}>klik disini untuk login</a></h1>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

{% block script_foot %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
</script>
{% endblock script_foot %}

news/templates/news/news-index.html
{% extends 'news/base.html' %}
{% load static %}

{% block head %}
<title>News | Form Corona</title>
{% endblock head %}

{% block style %}
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@200;300;400;500;600;700&display=swap"rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" />
<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/news-ui.css' %}" />
{% endblock style %}

{% block script_head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
{% endblock script_head %}

{% block content %}


{% comment %} {% if news %} {% endcomment %}
<div class="container pt-10 my-12 mx-auto px-4 md:px-12">
  <div id="news-box" class="flex flex-wrap -mx-1 lg:-mx-4 m-auto">

  {% comment %} {% for i in news %}
  <div class="content-center my-1 px-1 w-full m-auto max-w-xl md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
    <div id={{ i.id }} class="transform hover:-translate-y-2 duration-500 ease-in-out -full md:w-3/3 p-6 flex flex-col flex-grow flex-shrink">
      <div class="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow-lg">
        <a href={{ i.url }} target="_blank">
        {% if i.img %}
          <img src={{ i.img }} class="object-cover h-full w-full rounded-t">
        {% endif %}
          <p class="w-full text-gray-600 text-xs md:text-sm pt-6 px-6">{{ i.outlet }}</p>
          <div class="w-full font-bold text-xl text-gray-900 px-6">{{ i.title }}</div>
        {% if i.description %}
          <p class="text-gray-800 mt-3 font-serif text-base px-6 mb-5">{{ i.description }}</p>
        {% endif %}
        </a>
      </div>
    </div>
  </div>
  {% endfor %} {% endcomment %}
  </div>
</div>
{% comment %} {% else %}
  <h3>Something is wrong. There's no news :(</h3>
{% endif %} {% endcomment %}
<a href={% url "news:hoax" %} target="_blank">
  <button class="learn-more fixed bottom-0 left-0 m-5 focus:outline-none">
      <span class="circle" aria-hidden="true">
        <i class="icon arrow"></i>
      </span>
      <span class="button-text">Lapor Hoax</span>
  </button>
</a>

<button id="back-to-top" class="learn-more fixed bottom-20 left-0 m-5 focus:outline-none">
      <span class="circle noani" aria-hidden="true">
        <i class="icon arrow top"></i>
      </span>
  </button>
{% endblock %}

{% block script_foot %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src={% static 'js/script.js' %} type="text/javascript"></script>
{% endblock script_foot %}

news/templates/news/success.html
{% extends 'form/base.html' %}
{% load static %}

<!-- Title -->
{% block title %}Success!{% endblock title %}

<!-- Header -->
{% block header %}
{% include 'home/navbar.html' %}
{% endblock  %}

<!-- Content -->
{% block content %}
    <div class="container d-flex h-100">
        <div class="row align-self-center w-100">
          <div class="col-lg-4 col-md-6 col-sm-6 mx-auto">
            <div class="container" align="center">
              <h3>FORM SAVED!</h3>
              <a class="btn btn-success btn-xl my-4" href="{% url 'home:index' %}">Go Home</a>
            </div>
          </div>
        </div>
      </div>
{% endblock %}