TK2_PPW/urls.py
import django
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_register.urls')),

    path('', include('home.urls')),
    path('form/', include('form.urls')),
    path('info/', include('info.urls')),
    path('article/', include('article.urls')),
    path('news/', include('news.urls')),
]

form/urls.py
from django.urls import path

from . import views
from form.views import UserCreateView

app_name = 'form'

urlpatterns = [
    path('', UserCreateView.as_view(), name='form'),
    path('success/', views.success, name='success'),
    path('patient/', views.patient_list, name='patient_list'),
    path('details/<int:pk>', views.patient_details, name='patient_details'),
    path('delete/<int:pk>', views.delete_patient, name='delete_patient'),
    path('search/', views.search_patient, name='search_patient'),
    path('case/', views.add_case, name='add_case'),
]

home/urls.py
from django.urls import path
from . import views

app_name= 'home'

urlpatterns = [
    path('', views.index, name='index')
]

login_register/urls.py
from django.urls import path

from .views import sign_up_page, loginView,  logoutUser

app_name= 'login_register'

urlpatterns = [
    path('signup/', sign_up_page, name='signup'),
    path('login/', loginView, name='login'),
    # path('loginAPI/', loginAPI, name='loginAPI'),
    path('logout/', logoutUser, name='logout')
]

form/models.py
from django.db import models


class Patient(models.Model):
    name = models.CharField(max_length=70)
    age = models.PositiveIntegerField()
    SEX_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]
    sex = models.CharField(
        max_length=6,
        choices=SEX_CHOICES,
    )
    job = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    province = models.CharField(max_length=30)
    medical_history = models.CharField(max_length=80)
    education = models.CharField(max_length=30)
    symptoms = models.CharField(max_length=1000)


class Case(models.Model):
    date = models.CharField(max_length=10)
    time = models.CharField(max_length=5)
    hospital = models.CharField(max_length=30)
    doctor = models.CharField(max_length=30)
    patient_id = models.IntegerField()

form/forms.py
from django import forms

from .models import Case


class CaseForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = '__all__'
        widgets = {
            'hospital': forms.TextInput(attrs={'class': 'form-control'}),
            'doctor': forms.TextInput(attrs={'class': 'form-control'}),
        }

form/views.py
import json
import requests

from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.views.decorators.csrf import csrf_exempt

from .forms import CaseForm
from .models import Patient, Case


class UserCreateView(CreateView):
    model = Patient
    template_name = 'form/form.html'
    success_url = 'success'
    fields = (
        'name',
        'age',
        'sex',
        'job',
        'city',
        'province',
        'medical_history',
        'education',
        'symptoms',
    )

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def success(request):
    return render(request, 'form/success.html')


def patient_list(request):
    patients = Patient.objects.all()
    is_empty = False
    if not patients:
        is_empty = True
    context = {
        'patients': patients,
        'is_empty': is_empty,
    }
    return render(request, 'form/list.html', context)


def patient_details(request, pk):
    patient = Patient.objects.get(id=pk)
    isEmpty = False
    cases = Case.objects.all()
    if not cases:
        isEmpty = True
    context = {'patient': patient, 'cases': cases, 'isEmpty': isEmpty}
    return render(request, 'form/details.html', context)


def delete_patient(request, pk):
    if request.method == "POST":
        patient = Patient.objects.get(id=pk)
        patient.delete()
        messages.success(request, (f"{patient} deleted."))
    return redirect('form:patient_list')


def search_patient(request):
    query = request.GET.get('q')
    field = request.GET.get('field')
    if query:
        if field == 'name':
            results = Patient.objects.filter(name__startswith=query)
        elif field == 'age':
            results = Patient.objects.filter(age__startswith=query)
        elif field == 'sex':
            results = Patient.objects.filter(sex__startswith=query)
        elif field == 'job':
            results = Patient.objects.filter(job__startswith=query)
        elif field == 'city':
            results = Patient.objects.filter(city__startswith=query)
        elif field == 'province':
            results = Patient.objects.filter(province__startswith=query)
        elif field == 'medical_history':
            results = Patient.objects.filter(medical_history__icontains=query)
        elif field == 'education':
            results = Patient.objects.filter(education__startswith=query)
        else:
            results = Patient.objects.filter(symptoms__icontains=query)
    else:
        results = Patient.objects.all()
    data = list(results.values())
    return JsonResponse(data, safe=False)


@csrf_exempt
def add_case(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        case = Case(
            date=data['date'],
            time=data['time'],
            hospital=data['hospital'],
            doctor=data['doctor'],
            patient_id=data['id'],
        )
        case.save()
        return HttpResponse(status=200)

form/templates/form/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Arvo&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Odibee+Sans&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'home/images/icons8_virus_48_xbi_icon.ico' %}">
    <title>Form Corona - {% block title %}{% endblock title %}</title>
    <script>
        window.onscroll = () => {
            if (window.innerHeight + window.scrollY >= document.querySelector('#main').offsetHeight) {
                document.querySelector('.navbar').style.background = '#00ac96';
            } else {
                document.querySelector('.navbar').style.background = 'transparent';
            }
        }
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
</head>
<body>
    <!-- Header -->
    {% block header %}
    {% endblock %}

    <!-- Fill content -->
    {% block content %}
    {% endblock content %}
    
    <!-- Footer -->
    {% include "home/footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
    <script src="{% static 'form/js/script.js' %}"></script>
</body>
</html>

form/templates/form/details.html
{% extends 'form/base.html' %}
{% load static %}
{% block title %}Patient Details{% endblock title %}

<!-- Header -->
{% block header %}
{% include 'home/navbar.html' %}
{% endblock  %}

{% block content %}
    <div class="container pt-10 my-12 mx-auto px-4 md:px-12">
        <div class="mx-auto container max-w-7xl md:w-3/4 shadow-md">
            <div class="p-4 text-3xl text-center">
                <div class="max-w-sm mx-auto md:w-full md:mx-0">
                    <div class="inline-flex items-center space-x-4 ">
                        <h1 class="text-gray-600">Patient Details</h1>
                    </div>
                </div>
            </div>
            <div class="bg-gray-100 p-4 border-t-2 bg-opacity-5 border-green-400 rounded-t text-center"></div>
                <div class="container pb-4">
                    <h3 class="display-4">{{ patient.name }} <span class="lead">#<span id="patient-id">{{ patient.id }}</span></span></h3>
                    <div class="row">
                        <div class="col">
                            <table class="table table-borderless w-auto">
                                <tbody>
                                    <tr>
                                        <th>Age:</th>
                                        <td>{{ patient.age }}</td>
                                    </tr>
                                    <tr>
                                        <th>Sex:</th>
                                        <td>{{ patient.sex }}</td>
                                    </tr>
                                    <tr>
                                        <th>Job:</th>
                                        <td>{{ patient.job }}</td>
                                    </tr>
                                    <tr>
                                        <th>City:</th>
                                        <td>{{ patient.city }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col">
                            <table class="table table-borderless w-auto">
                                <tbody>
                                    <tr>
                                        <th>Province:</th>
                                        <td>{{ patient.province }}</td>
                                    </tr>
                                    <tr>
                                        <th>Medical History:</th>
                                        <td>{{ patient.medical_history }}</td>
                                    </tr>
                                    <tr>
                                        <th>Education:</th>
                                        <td>{{ patient.education }}</td>
                                    </tr>
                                    <tr>
                                        <th>Symptoms:</th>
                                        <td>{{ patient.symptoms }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="container pb-4">
                    <h2 class="text-2xl">Case List</h2>
                    <button id="add-case" class="btn btn-warning my-3" role="button">Add Case</button>
                    <br>
                    <table id="case-table" class="table table-responsive">
                        <thead>
                            <tr>
                                <th scope="col" style="width: 23%">Date Recorded</th>
                                <th scope="col" style="width: 15%">Time</th>
                                <th scope="col" style="width: 31%">Hospital</th>
                                <th scope="col" style="width: 31%">Doctor</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for case in cases %}
                                {% if case.patient_id == patient.id %}
                                    <tr>
                                        <td>{{ case.date }}</td>
                                        <td>{{ case.time }}</td>
                                        <td>{{ case.hospital }}</td>
                                        <td>{{ case.doctor }}</td>
                                    </tr>
                                {% endif %}
                                {% if isEmpty %}
                                    <tr><td colspan="4">Empty</td></tr>
                                {% endif %}
                            {% endfor %}
                            <tr id="blank-row"></tr>
                            <tr id="input-row">
                                <td><input type="date" class="form-control" id="date-picker"></td>
                                <td><input type="time" class="form-control" id="time-picker"></td>
                                <td><input type="text" class="form-control" id="hospital-input"></td>
                                <td><input type="text" class="form-control" id="doctor-input"></td>
                            </tr>
                            <tr id="save-row">
                                <td></td>
                                <td></td>
                                <td></td>
                                <td align="right"><button id="save-case" class="btn btn-info" role="button">Save</button></td>
                            </tr>
                        </tbody>
                    </table>
                    <a class="btn btn-outline-primary mt-4" href="{% url 'form:patient_list' %}" role="button">BACK</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

form/templates/form/form.html
{% extends 'form/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<!-- Title -->
{% block title %}Form{% endblock title %}

<!-- Header -->
{% block header %}
    {% include 'home/navbar.html' %}
{% endblock %}

<!-- Content -->
{% block content %}
    <div class="container pt-10 my-12 mx-auto px-4 md:px-12">
        <div class="mx-auto container max-w-7xl md:w-3/4 shadow-md">
            <div class="p-4 text-3xl text-center">
                <div class="max-w-sm mx-auto md:w-full md:mx-0">
                    <div class="inline-flex items-center space-x-4 ">
                        <h1 class="text-gray-600">Patient Form</h1>
                    </div>
                </div>
            </div>
            {% if user.is_authenticated %}
                <div class="bg-gray-100 p-4 border-t-2 bg-opacity-5 border-green-400 rounded-t text-center">
                    <div class="max-w-sm mx-auto md:w-full md:mx-0">
                        <div class="inline-flex items-center space-x-4">
                            <h1 class="text-gray-600">Silakan isi form data pasien di bawah ini.</h1>
                        </div>
                    </div>
                </div>
                <form method="post" novalidate>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6">
                            {{ form.name|as_crispy_field }}
                        </div>
                        <div class="col-3">
                            {{ form.city|as_crispy_field }}
                        </div>
                        <div class="col-3">
                            {{ form.province|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            {{ form.age|as_crispy_field }}
                        </div>
                        <div class="col-3">
                            {{ form.sex|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.medical_history|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            {{ form.job|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.education|as_crispy_field }}
                        </div>
                    </div>
                    {{ form.symptoms|as_crispy_field }}
                    <div class="p-2 bg-opacity-5 rounded-t text-center">
                        <div class="max-w-sm mx-auto md:w-full md:mx-0">
                            <input type="submit" value="Simpan" class="inline-block px-6 py-2 text-xs font-medium leading-6 text-center text-white uppercase transition bg-green-500 rounded shadow ripple hover:shadow-lg hover:bg-green-600 focus:outline-none">
                        </div>
                    </div>
                </form>
            {% else %}
                <div class="bg-gray-100 p-4 border-t-2 bg-opacity-5 border-green-400 rounded-t text-center">
                    <div class="max-w-sm mx-auto md:w-full md:mx-0">
                        <div class="inline-flex items-center space-x-4">
                            <h1 class="text-gray-600">Anda belum login,</h1>
                        </div>
                        <div class="inline-flex items-center space-x-4">
                            <h1 class="text-gray-600 font-bold"><a href="{% url 'login_register:login' %}">klik disini untuk login</a>
                            </h1>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

form/templates/form/list.html
{% extends 'form/base.html' %}
{% load static %}
{% block title %}Patient List{% endblock title %}

<!-- Header -->
{% block header %}
{% include 'home/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container pt-10 my-12 mx-auto px-4 md:px-12">
        <div class="mx-auto container max-w-7xl md:w-3/4 shadow-md">
            <div class="p-4 text-3xl text-center">
                <div class="max-w-sm mx-auto md:w-full md:mx-0">
                    <div class="inline-flex items-center space-x-4">
                        <h1 class="text-gray-600">Patient List</h1>
                    </div>
                </div>
            </div>
            {% if user.is_authenticated %}
                <div class="bg-gray-100 p-4 border-t-2 bg-opacity-5 border-green-400 rounded-t text-right">
                    <div class="inline-flex items-center space-x-4">
                        <select id="field-selector" class="form-control">
                            <option value="name">Name</option>
                            <option value="age">Age</option>
                            <option value="sex">Sex</option>
                            <option value="job">Job</option>
                            <option value="city">City</option>
                            <option value="province">Province</option>
                            <option value="medical_history">Medical history</option>
                            <option value="education">Education</option>
                            <option value="symptoms">Symptoms</option>
                        </select>
                        <input id="search-bar" class="w-full h-10 px-3 text-base text-gray-700 placeholder-gray-600 border rounded-lg focus:shadow-outline" type="text" placeholder="Search"/>                        
                    </div>
                </div>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
                <div id="list-container" class="container">
                    {% for patient in patients %}
                        <div class="pb-4 bg-opacity-5 rounded-t">
                            <div class="card mt-3">
                                <div class="card-body d-flex justify-content-between flex-column flex-md-row">
                                    <div>
                                        <a href="{% url 'form:patient_details' patient.id %}">
                                            <h5 class="card-title">{{ patient.name }}</h5>
                                        </a>
                                        <h6 class="card-subtitle mb-2 text-muted">{{ patient.age }} ({{ patient.sex }})</h6>
                                    </div>
                                    <form action="{% url 'form:delete_patient' patient.id %}" method="POST">
                                        {% csrf_token %}
                                        <button class="btn btn-danger card-link mt-2 mr-md-4 align-self-center" type="input">
                                            DELETE
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% if is_empty %}
                    <div class="p-4 bg-opacity-5 rounded-t text-center">
                        <div class="max-w-sm mx-auto md:w-full md:mx-0">
                            <p class="lead">Pasien kosong. Silakan isi form untuk menambah pasien.</p>
                        </div>
                    </div>
                {% endif %}
            {% else %}
                <div class="bg-gray-100 p-4 border-t-2 bg-opacity-5 border-green-400 rounded-t text-center">
                    <div class="max-w-sm mx-auto md:w-full md:mx-0">
                        <div class="inline-flex items-center space-x-4">
                            <h1 class="text-gray-600">Anda belum login,</h1>
                        </div>
                        <div class="inline-flex items-center space-x-4">
                            <h1 class="text-gray-600 font-bold"><a href="{% url 'login_register:login' %}">klik disini untuk login</a>
                            </h1>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

form/templates/form/success.html
{% extends 'form/base.html' %}
{% load static %}

<!-- Title -->
{% block title %}Success!{% endblock title %}

<!-- Header -->
{% block header %}
    {% include 'home/navbar.html' %}
{% endblock  %}

<!-- Content -->
{% block content %}
    <div class="container pt-10 my-12 mx-auto px-4 md:px-12">
        <div class="mx-auto container max-w-7xl md:w-3/4 shadow-md">
            <div class="p-4 text-3xl text-center">
                <div class="max-w-sm mx-auto md:w-full md:mx-0">
                    <div class="inline-flex items-center space-x-4 ">
                        <h1 class="text-gray-600">FORM SAVED!</h1>
                    </div>
                </div>
            </div>
            <div class="bg-gray-100 p-4 border-t-2 bg-opacity-5 border-green-400 rounded-t text-center">
                <div class="max-w-sm mx-auto md:w-full md:mx-0">
                    <div class="inline-flex items-center space-x-4">
                        <a class="btn btn-success btn-xl my-4" href="{% url 'home:index' %}">Go Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}